### ISSUE TITLE
Provide JAR

### ISSUE THREAD

**Issue by jangrewe** [kakawait/sonar-gitlab-plugin#18]
Hi, thanks for keeping this plugin updated!

Would you be so kind and provide a JAR (added to the releases page) that can be downloaded? This would make it a lot easier to included this in automated deployments. =)

thanks!

**Comment by kakawait** [comment]
Hi thank for feedback. I have to push some mandatory commit to fix bug we met on our env.
Just after yes I will upload jar

**Comment by jangrewe** [comment]
Great, thank you!

**Comment by kakawait** [comment]
Keep it open else I may forget it lol

**Comment by jangrewe** [comment]
@kakawait a friendly reminder ;-)

**Comment by kakawait** [comment]
@jangrewe thank I forget... Just added and update `README`

plugin is not 100% perfect but feel free to open issue or PR I will be more *reactive* for now

**Comment by jangrewe** [comment]
Thank you very much, i'll give it a spin tomorrow in the office! =)
