### ISSUE TITLE
Sonar overrides plugin during updates

### ISSUE THREAD

**Issue by dve** [kakawait/sonar-gitlab-plugin#22]
Sonarqubes update center overrides this plugin with the one from talanlabs. I guess its because it has exactly the same name.

**Comment by kakawait** [comment]
Hum that weird. I will check that I think there is some meta or id to change somewhere :)

**Comment by kakawait** [comment]
I'm not maintaining the project anymore (please refer to original project https://github.com/gabrie-allaigre/sonar-gitlab-plugin)
